import cv2
import os
import glob
from particle_analysis import find_inner_holes_contours

# --- 1. Configuration: Point to the saved debug files ---
# These files are generated by a batch script (e.g., batch_run_NN_DB_4c.py) 
# when its 'SAVE_DEBUG_INPUTS' flag is set to True.
# You must change the folder and prefix to match the specific case you want to debug.

INPUT_DIR = r"D:\Ingenieurpraixs\test2" # The folder where your results are.

# Automatically find files ending with specific suffixes
gray_files = glob.glob(os.path.join(INPUT_DIR, "*_debug_input_gray.png"))
mask_files = glob.glob(os.path.join(INPUT_DIR, "*_debug_input_mask.png"))

# Use the first found file (assuming you are debugging one case at a time in this folder)
GRAY_IMAGE_PATH = gray_files[0] if gray_files else ""
MASK_IMAGE_PATH = mask_files[0] if mask_files else ""

print(f"Auto-detected inputs:\n  Gray: {os.path.basename(GRAY_IMAGE_PATH) if GRAY_IMAGE_PATH else 'None'}\n  Mask: {os.path.basename(MASK_IMAGE_PATH) if MASK_IMAGE_PATH else 'None'}")


# --- 2. Parameters for find_inner_holes_contours ---
# This is where you can quickly test different parameters.
# These values are copied from batch_run_NN_DB_4c.py as a starting point.
HOLE_PARAMS = {
    "min_area": 20,
    "max_area": 50000,
    "min_circularity": 0.6,   # [调整] 既然优化了轮廓，可以稍微提高圆度要求来过滤真正的乱形状
    "block_size": 21,         # [调整] 稍微减小 (原41)，让阈值计算更关注局部，避免受远处光照影响
    "c_value": 8,            # [关键] 大幅提高 (原3 -> 10)。这会让孔洞轮廓收缩，断开与噪音的粘连。
    "erosion_size": 25,
    "debug": True,          # Set to True to see intermediate images per particle
    "detect_dark": True,    # True for dark holes, False for bright spots
    "predict_4c": True,     # Set to False to debug individual hole detection
    "return_data": True,
    "use_median_blur": True,  # [关键] 开启中值滤波，抗噪且不模糊边缘
    "median_ksize": 5,        # 配合中值滤波，5x5 通常足够
    "opening_ksize": 9        # 保持适度的开运算来切断细小连接
}

# --- 3. Output Configuration ---
if GRAY_IMAGE_PATH:
    _prefix = os.path.basename(GRAY_IMAGE_PATH).replace("_debug_input_gray.png", "")
    OUTPUT_IMAGE_PATH = os.path.join(INPUT_DIR, f"{_prefix}_debug_holes_output.png")
else:
    OUTPUT_IMAGE_PATH = os.path.join(INPUT_DIR, "debug_holes_output.png")

def main():
    """
    This script allows for rapid debugging of the find_inner_holes_contours function.
    
    How to use:
    1. Run your main batch script (e.g., batch_run_NN_DB_4c.py) with its 
       'SAVE_DEBUG_INPUTS' flag set to True.
    2. This will save `..._debug_input_gray.png` and `..._debug_input_mask.png` files.
    3. Point the INPUT_DIR and PREFIX variables above to these files.
    4. Adjust the parameters in HOLE_PARAMS and run this script.
    5. Check the output image and the console for debug information.
    
    This process is much faster than re-running the entire analysis pipeline.
    """
    print("=== Starting Hole Detection Debug Script ===")

    # --- Load Input Images ---
    if not os.path.exists(GRAY_IMAGE_PATH):
        print(f"[ERROR] Gray image not found: {GRAY_IMAGE_PATH}")
        return
    if not os.path.exists(MASK_IMAGE_PATH):
        print(f"[ERROR] Mask image not found: {MASK_IMAGE_PATH}")
        return

    print(f"Loading gray image: {os.path.basename(GRAY_IMAGE_PATH)}")
    image_gray = cv2.imread(GRAY_IMAGE_PATH, cv2.IMREAD_GRAYSCALE)
    
    print(f"Loading mask image: {os.path.basename(MASK_IMAGE_PATH)}")
    structure_mask = cv2.imread(MASK_IMAGE_PATH, cv2.IMREAD_GRAYSCALE)

    if image_gray is None or structure_mask is None:
        print("[ERROR] Failed to load one or both images.")
        return

    # --- Run the function ---
    print("\nRunning find_inner_holes_contours with parameters:")
    for key, value in HOLE_PARAMS.items():
        print(f"  - {key}: {value}")
    
    find_inner_holes_contours(
        image_gray=image_gray,
        structure_mask=structure_mask,
        save_path=OUTPUT_IMAGE_PATH,
        **HOLE_PARAMS
    )

    print(f"\n=== Debugging Complete ===")
    print(f"-> Output visualization saved to: {OUTPUT_IMAGE_PATH}")
    if HOLE_PARAMS.get("debug"):
        print(f"-> Intermediate debug files (e.g., debug_particle_*) saved in the same directory.")

if __name__ == "__main__":
    main()